parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: "module"

env:
  browser: true
  jest: true
  es6: true

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  semi:
    - error
    - never
  no-console:
    - off
  react/prop-types:
    - ignore
  quotes:
    - error
    - double
  react/no-find-dom-node:
    - ignore
  no-debugger:
    - off
