version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.11.0-jessie-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install --no-audit
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Format
          command: npm run format && git diff --exit-code -- src itest
      - run:
          name: Build
          command: npm run build
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Flow
          command: npm run flow
      - run:
          name: Unit Tests
          command: npm test -- --maxWorkers=2 --ci
  integration_tests:
    docker:
      # Built from https://github.com/looky-cloud/rug/blob/master/.circleci/Dockerfile.
      - image: gcr.io/quixotic-strand-159502/rug@sha256:349ab7134e0dc210ec511452b922f6d7e0173c38d0cca52822f6aaa7b85e41d7
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - checkout
      - run:
          name: Integration tests
          command: ./.circleci/rug-component.sh
      - store_artifacts:
          path: /var/tmp/looky/logs
      - store_artifacts:
          path: /home/circleci/.npm/_logs
workflows:
  version: 2
  main:
    jobs:
      - build
      - integration_tests:
          requires:
            - build
